// src/utils/myTicketMock.ts

import { ITicket } from '../types/ticket';
import { Tag } from '../types/tag';

export const myTicketMock: ITicket[] = [
  {
    _id: '1',
    title: 'Server Downtime',
    description:
      'The application server has been down for over an hour, causing disruptions to all services.',
    priority: 'High',
    category: 'Technical Issue',
    application: 'Loga Beauty',
    status: 'Critical',
    assignedTo: 'IT Support Team',
    department: 'IT',
    date: '2023-10-10T14:30:00Z',
    dueDate: '2023-10-11T14:30:00Z',
    tags: [Tag.Infrastructure, Tag.Urgent, Tag.SystemFailure],
    comments: [],
    attachments: [],
    activityLog: [],
    createdBy: 'chris',
  },
  {
    _id: '2',
    title: 'Data Loss in Employee Records',
    description:
      'Several employee records appear to be missing after a system update.',
    priority: 'High',
    category: 'Bug Report',
    application: 'TimeSync',
    status: 'Pending',
    assignedTo: 'Database Team',
    department: 'HR',
    date: '2023-10-11T09:15:00Z',
    dueDate: '2023-10-13T17:00:00Z',
    tags: [Tag.DataLoss, Tag.SystemUpdate, Tag.Urgent],
    comments: [],
    attachments: [],
    activityLog: [],
    createdBy: 'chris',
  },
  {
    _id: '3',
    title: 'Login Authentication Failure',
    description:
      'Users are unable to log into the system due to failed authentication requests.',
    priority: 'Medium',
    category: 'Technical Issue',
    application: 'GatherPlux',
    status: 'Open',
    assignedTo: '',
    department: 'IT',
    date: '2023-10-12T08:45:00Z',
    dueDate: '2023-10-15T17:00:00Z',
    tags: [Tag.UserAuth, Tag.LoginIssue, Tag.Urgent],
    comments: [],
    attachments: [],
    activityLog: [],
    createdBy: 'chris',
  },
  {
    _id: '4',
    title: 'Slow Performance in Dashboard',
    description:
      'The dashboard is experiencing significant performance slowdowns, especially during peak hours.',
    priority: 'Low',
    category: 'Feature Request',
    application: 'BookMiz',
    status: 'Pending',
    assignedTo: '',
    department: 'Sales',
    date: '2023-10-13T11:00:00Z',
    dueDate: '2023-10-20T17:00:00Z',
    tags: [Tag.Performance, Tag.UserExperience, Tag.NonUrgent],
    comments: [],
    attachments: [],
    activityLog: [],
    createdBy: 'chris',
  },
  {
    _id: '5',
    title: 'Payment Gateway Failure',
    description:
      'Payments are failing to process for users attempting to subscribe or purchase services.',
    priority: 'High',
    category: 'Technical Issue',
    application: 'Loga Beauty',
    status: 'Critical',
    assignedTo: 'Finance Team',
    department: 'Finance',
    date: '2023-10-14T15:20:00Z',
    dueDate: '2023-10-15T17:00:00Z',
    tags: [Tag.PaymentIssue, Tag.Urgent, Tag.Finance],
    comments: [],
    attachments: [],
    activityLog: [],
    createdBy: 'chris',
  },
  {
    _id: '6',
    title: 'Employee Absence Report Issue',
    description:
      'The system is failing to generate accurate absence reports for department heads.',
    priority: 'Medium',
    category: 'Bug Report',
    application: 'TimeSync',
    status: 'Pending',
    assignedTo: '',
    department: 'HR',
    date: '2023-10-15T10:30:00Z',
    dueDate: '2023-10-22T17:00:00Z',
    tags: [Tag.HRManagement, Tag.Reports, Tag.NonUrgent],
    comments: [],
    attachments: [],
    activityLog: [],
    createdBy: 'chris',
  },
  {
    _id: '7',
    title: 'Payroll Discrepancy',
    description:
      'There is a discrepancy in payroll calculations for the last two pay periods for multiple employees.',
    priority: 'High',
    category: 'Technical Issue',
    application: 'Loga Beauty',
    status: 'Open',
    assignedTo: 'Payroll Team',
    department: 'Finance',
    date: '2023-10-16T09:45:00Z',
    dueDate: '2023-10-18T17:00:00Z',
    tags: [Tag.Payroll, Tag.Finance, Tag.Urgent],
    comments: [],
    attachments: [],
    activityLog: [],
    createdBy: 'chris',
  },
  {
    _id: '8',
    title: 'Shift Scheduling Conflict',
    description:
      'Multiple employees have overlapping shifts despite being in different departments, causing resource conflicts.',
    priority: 'Medium',
    category: 'Feature Request',
    application: 'TimeSync',
    status: 'Open',
    assignedTo: '',
    department: 'HR',
    date: '2023-10-17T14:00:00Z',
    dueDate: '2023-10-24T17:00:00Z',
    tags: [Tag.HR, Tag.Scheduling, Tag.Urgent],
    comments: [],
    attachments: [],
    activityLog: [],
    createdBy: 'chris',
  },
  {
    _id: '9',
    title: 'Employee Profile Update Error',
    description:
      'Users are unable to update their personal information or change their profile pictures.',
    priority: 'Low',
    category: 'Bug Report',
    application: 'GatherPlux',
    status: 'Pending',
    assignedTo: '',
    department: 'IT',
    date: '2023-10-18T13:15:00Z',
    dueDate: '2023-10-25T17:00:00Z',
    tags: [Tag.Profile, Tag.HRManagement, Tag.NonUrgent],
    comments: [],
    attachments: [],
    activityLog: [],
    createdBy: 'chris',
  },
];
